services:
  brave-search:
    image: docker.io/mcp/brave-search
    environment:
      BRAVE_API_KEY: ${BRAVE_MCP_API}
      BRAVE_MCP_TRANSPORT: http
      BRAVE_MCP_PORT: 8080
    ports:
      - "8001:8080"

  files-mcp:
    build: ./files
    ports:
      - "8002:8000"
    volumes:
      - ../../data/mcp-files:/data/files

  string-mcp:
    build: ./string
    ports:
      - "8003:8000"
    volumes:
      - ../../data/mcp-files:/data/files

  image-mcp:
    build: ./image
    ports:
      - "8004:8000"
    volumes:
      - ../../data/mcp-files:/data/files
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
